"""
filters.py

Filter Registry and FILTER.RES Generation
---------------------------------------------------------

Resolves each photometry band to a transmission curve and writes the
run-local eazy inputs:

  - broadband curves come from the vendored package data
    (``data/filters/<Band>.dat``, regenerated by ``vendor_filters.py``) or
    from ``config.extra_filters`` (checked first);
  - SPHEREx channels become per-object rectangular tophats built from the
    CSV's wave_um/bandwidth_um columns -- eazy applies its own
    photon-counting 1/lambda weighting inside the bandpass integrals;
  - the FILTER.RES text is assembled from
    ``eazy.filters.FilterDefinition.for_filter_file()`` blocks, which embed
    the ``lambda_c=`` tag eazy's reader requires in each header line.

Data products (per run directory):
  FILTER.RES        the generated eazy filter file (fit order, 1-indexed)
  FILTER.RES.info   human-readable index: number, band, pivot wavelength
  zphot.translate   f_<band> -> F<n> / e_<band> -> E<n> column mapping

Requirements:
  - numpy; eazy (build_filter_res only)
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from .config import FILTER_DATA_DIR, FitConfig
from .data import is_spherex

SPHEREX_TOPHAT_SAMPLES = 25


def available_filters() -> list[str]:
    """Band names with a vendored transmission curve."""
    return sorted(p.stem for p in FILTER_DATA_DIR.glob("*.dat"))


def get_filter_curve(band: str, *, extra_filters: dict | None = None) -> tuple[np.ndarray, np.ndarray]:
    """Transmission curve for a broadband filter.

    Parameters
    ----------
    band : str
        CSV band name (e.g. "CFHT_u").
    extra_filters : dict or None
        ``{band -> curve file}`` overrides, checked before the vendored set.

    Returns
    -------
    wave : np.ndarray
        Wavelength in Angstrom.
    throughput : np.ndarray
        Dimensionless throughput (normalization is irrelevant to eazy).
    """
    path = None
    if extra_filters and band in extra_filters:
        path = Path(extra_filters[band]).expanduser()
    else:
        candidate = FILTER_DATA_DIR / f"{band}.dat"
        if candidate.exists():
            path = candidate
    if path is None or not path.exists():
        raise ValueError(
            f"no transmission curve for band {band!r}: not in the vendored set "
            f"(see vendor_filters.py) and not in config.extra_filters")
    curve = np.loadtxt(path)
    return curve[:, 0].astype(float), curve[:, 1].astype(float)


def make_spherex_tophat(wave_um: float, bandwidth_um: float, *,
                        n_samples: int = SPHEREX_TOPHAT_SAMPLES) -> tuple[np.ndarray, np.ndarray]:
    """Rectangular tophat curve for one SPHEREx channel.

    Parameters
    ----------
    wave_um : float
        Channel center wavelength (micron).
    bandwidth_um : float
        Channel full width (micron).
    n_samples : int
        Samples across the open interval. [default: 25]

    Returns
    -------
    wave : np.ndarray
        Wavelength in Angstrom, with zero-throughput endpoints just outside
        the band so interpolation cannot extrapolate the edge.
    throughput : np.ndarray
        1 inside the channel, 0 at the padded endpoints.
    """
    center = float(wave_um) * 1e4
    width = float(bandwidth_um) * 1e4
    lo, hi = center - width / 2.0, center + width / 2.0
    pad = max(width * 1e-3, 1e-3)
    wave = np.concatenate([[lo - pad], np.linspace(lo, hi, n_samples), [hi + pad]])
    throughput = np.concatenate([[0.0], np.ones(n_samples), [0.0]])
    return wave, throughput


def build_filter_res(band_meta, *, config: FitConfig, res_path) -> dict[str, int]:
    """Write the run's FILTER.RES (+ .info) and return the band numbering.

    Parameters
    ----------
    band_meta : Table
        One row per band in fit order: ``band, wave_um, bandwidth_um``
        (``data.band_metadata``).
    config : FitConfig
        Supplies ``extra_filters`` and the SPHEREx prefix.
    res_path : str or Path
        Output FILTER.RES path; the ``.info`` sidecar is written next to it.

    Returns
    -------
    band_numbers : dict[str, int]
        Band name -> 1-based filter number (eazy translate convention).
    """
    # eazy import kept local so the input modules stay importable without it.
    from eazy.filters import FilterDefinition

    blocks = []
    info_lines = []
    band_numbers: dict[str, int] = {}
    for number, row in enumerate(band_meta, start=1):
        band = str(row["band"])
        if is_spherex(band, config.spherex_prefix):
            wave, thru = make_spherex_tophat(row["wave_um"], row["bandwidth_um"])
        else:
            wave, thru = get_filter_curve(band, extra_filters=config.extra_filters)
        fdef = FilterDefinition(name=band, wave=wave, throughput=thru)
        blocks.append(fdef.for_filter_file())
        info_lines.append(f"{number:4d} {band:16s} lambda_c= {fdef.pivot:.4e}")
        band_numbers[band] = number

    res_path = Path(res_path)
    res_path.write_text("\n".join(blocks) + "\n")
    Path(f"{res_path}.info").write_text("\n".join(info_lines) + "\n")
    return band_numbers


def write_translate(band_numbers: dict[str, int], translate_path) -> None:
    """Write the eazy translate file mapping catalog columns to filters.

    eazy-py requires a real translate file (passing None crashes); the
    catalog columns are ``f_<band>`` / ``e_<band>`` and the numbers index
    the generated FILTER.RES in order.
    """
    lines = []
    for band, number in band_numbers.items():
        lines.append(f"f_{band} F{number}")
        lines.append(f"e_{band} E{number}")
    Path(translate_path).write_text("\n".join(lines) + "\n")
